### FindAll
GET http://localhost:3000/distribuidoras HTTP/1.1

### FindOne
GET http://localhost:3000/distribuidoras/1 HTTP/1.1

### Create
POST http://localhost:3000/distribuidoras HTTP/1.1
Content-Type: application/json

{
    "nome": "Lorem",
    "plataforma": "plat"
}

### Update
PATCH http://localhost:3000/distribuidoras/1 HTTP/1.1
Content-Type: application/json

{
    "nome": "Lorem",
    "plataforma": "platdassa"
}

### Delete
DELETE http://localhost:3000/distribuidoras/1 HTTP/1.1